version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "opravilo"
      POSTGRES_PASSWORD: "2282"
    ports:
      - "127.0.0.1:5432:5432"